[package]
name = "eloi-rs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
eloi-core = { path = "../eloi-core" }
eloi-engine = { path = "../eloi-engine" }
eloi-protocol = { path = "../eloi-protocol" }

[lints]
workspace = true
