[package]
name = "eloi-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
eloi-core = { path = "../eloi-core" }
eloi-simd = { path = "../eloi-simd" }
sha2 = "0.10.9"

[lints]
workspace = true
