[package]
name = "eloi-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
eloi-core = { path = "../eloi-core" }
eloi-engine = { path = "../eloi-engine" }
serde_json = "=1.0.151"

[target.'cfg(windows)'.dependencies]
windows = { version = "=0.61.3", features = ["Foundation", "Storage_Streams", "Web_Http", "Web_Http_Filters", "Web_Http_Headers"] }
windows-future = "=0.2.1"

[lints]
workspace = true
