"""Convert Eloi's frozen generated C++ repertoire into Rust constants."""

import argparse
import pathlib
import re


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=pathlib.Path, required=True)
    parser.add_argument("--output", type=pathlib.Path, required=True)
    args = parser.parse_args()
    text = args.input.read_text(encoding="utf-8")
    node_block, edge_block = text.split("inline constexpr std::array<Edge", 1)
    nodes = re.findall(r"\{0x([0-9a-f]+)ULL, (\d+), (\d+)\}", node_block)
    edges = re.findall(r"\{0x([0-9a-f]+), (\d+), (\d+)\}", edge_block)
    if len(nodes) != 5480 or len(edges) != 8092:
        raise SystemExit("unexpected frozen opening-table shape")
    lines = [
        "#![allow(clippy::unreadable_literal)]\n",
        "// Generated by scripts/generate_rust_openings.py; do not edit.\n",
        "pub(super) const NODES: &[(u64, u32, u16)] = &[\n",
    ]
    lines.extend(f"    (0x{k}, {first}, {count}),\n" for k, first, count in nodes)
    lines.append("];\npub(super) const EDGES: &[(u16, u16, u8)] = &[\n")
    lines.extend(f"    (0x{move}, {weight}, {family}),\n" for move, weight, family in edges)
    lines.append("];\n")
    args.output.write_text("".join(lines), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
